<?php

namespace WP\ProductBundle\Repository;

use WP\ProductBundle\Entity\Product;

/**
 * Product2MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product2MediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMaxPos(Product $product)
    {
        $query = $this->createQueryBuilder('p2m');
        $query->select('MAX(p2m.pos) AS max_pos');
        $query->where('p2m.product = :product')->setParameter('product', $product);
        $query->orderBy('p2m.pos', 'DESC');

        return $query->getQuery()->getOneOrNullResult();
    }
}
